<<<<<<< HEAD

=======
>>>>>>> de1837296ede2c7cd5058331e60b64e23fd01004
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aniketh Janardhan Reddy
email: anikethjr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Aniketh Janardhan Reddy, a student at the Birla Institute of Technology and Science, Pilani, India.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anikethjr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  anikethjr
linkedin_username: aniketh-reddy
facebook_username: anikethjr

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
<<<<<<< HEAD
#   - vendor/ruby/
=======
#   - vendor/ruby/
>>>>>>> de1837296ede2c7cd5058331e60b64e23fd01004
